// WINDOW DEFAULT DEFINES
#define WINDOW_WIDTH 700
#define WINDOW_HEIGHT 700

// GAME DEFAULTS DEFINES
#define DEFAULT_HEALTH 25.0f // 25
#define DEFAULT_SCORE 0.0f
#define DEFAULT_WAVE 1.0f
#define DEFAULT_FLY_COUNT 0.0f
#define DEFAULT_TOTAL_KILLS 0.0f

// TIMER DEFINES
#define WAVE_TIME 10
#define WAVE_TRANSITION_TIME 2

#define DEFAULT_ENEMY_TIMER 0.0f
#define DEFAULT_DEBUFF_TIMER 0.0f
#define DEFAULT_BUFF_TIMER 0.0f

#define DEFAULT_ENEMY_SPAWN_TIME 1.0f
#define DEFAULT_DEBUFF_SPAWN_TIME 15.0f
#define DEFAULT_BUFF_SPAWN_TIME 20.0f

#define DEFAULT_WAVE_UPDATE_TIME 0.0f
#define DEFAULT_WAVE_TRANSITION_TIME 0.0f